public enum Soortkamer {
    EENVOUDIGE_STUDIO_2_EENPERSOONSBEDDEN,
    EENVOUDIGE_TWEEPERSOONSKAMER,
    GRAND_STUDIO_2_EENPERSOONSBEDDEN,
    EXECUTIVE_STUDIO_2_EENPERSOONSBEDDEN,
    EXECUTIVE_STUDIO,
    EENVOUDIGE_VIERPERSOONSKAMER,
    FAMILIEKAMER
}
